In [2]:
import numpy as np

In [2]:
#0 dimension array
np.array(24)

array(24)

In [3]:
#1 Dimension array
np.array([1,2,3])

array([1, 2, 3])

In [4]:
#2 Dimension array
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#3 Dimension array
np.array([[[1,2,3], [1,2,3]],[[1,2,3],[1,2,3]]])

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [10]:
#print array shape 
num_array_1 = np.array([[[1,2,3], [1,2,3]],[[1,2,3],[1,2,3]]])
num_array_1.shape

(2, 2, 3)

In [21]:
#auto fill
num_array_2 = np.array([x for x in range(1,10)])
num_array_2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
num_array_3 = np.array([[x for x in range(1,10)], [y for y in range(10,20)]], dtype='object')
num_array_3

array([list([1, 2, 3, 4, 5, 6, 7, 8, 9]),
       list([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])], dtype=object)

In [23]:
#3x3 = 9 otherwise error reshape to 2D
num_array_2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#2x3x2 = 12 otherwise error reshape to 3D
num_array_2 = np.array([x for x in range(1,13)])
num_array_2.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [26]:
num_array_2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [28]:
#automatically calculates last dimension
num_array_2.reshape(2,3,-1)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [30]:
#automatically calculates dimension
num_array_2.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
A = np.array([[1,2,3],[2,2,3]])
B = np.array([3,4,5])

In [39]:
A

array([[1, 2, 3],
       [2, 2, 3]])

In [40]:
B

array([3, 4, 5])

In [41]:
#Numpy addition operation (column count should equal)
np.add(A,B)

array([[4, 6, 8],
       [5, 6, 8]])

In [43]:
#Numpy substraction operation (column count should equal)
np.subtract(A,B)

array([[-2, -2, -2],
       [-1, -2, -2]])

In [44]:
np.subtract(B,A)

array([[2, 2, 2],
       [1, 2, 2]])

In [45]:
#Numpy multiply
np.multiply(A,B)

array([[ 3,  8, 15],
       [ 6,  8, 15]])

In [46]:
#Numpy divide
np.divide(A,B)

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.5       , 0.6       ]])

In [48]:
#Square of values
np.power(A,2)

array([[1, 4, 9],
       [4, 4, 9]], dtype=int32)

In [49]:
np.power(A,B)

array([[  1,  16, 243],
       [  8,  16, 243]], dtype=int32)

In [56]:
#Numpy conditional statements
x = np.array([i for i in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.where(x%2==0,'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [58]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]
np.select(condlist, choicelist, default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [3]:
#Numpy Statistical functions
ArrayNew = np.array([[11,23,32],[14,52,16],[27,84,29]])
ArrayNew

array([[11, 23, 32],
       [14, 52, 16],
       [27, 84, 29]])

In [13]:
np.amin(ArrayNew)

11

In [17]:
np.amin(ArrayNew, axis=0)

array([11, 23, 16])

In [19]:
np.amin(ArrayNew, axis=1)

array([11, 14, 27])

In [20]:
np.amax(ArrayNew)

84

In [21]:
np.amax(ArrayNew, axis=0)

array([27, 84, 32])

In [22]:
np.amax(ArrayNew, axis=1)

array([32, 52, 84])

In [24]:
np.median(ArrayNew)

27.0

In [26]:
np.mean(ArrayNew)

32.0

In [28]:
np.var(ArrayNew)

471.1111111111111

In [4]:
np.std(ArrayNew)

21.70509412813294

In [6]:
np.percentile(ArrayNew, 50)

27.0

In [7]:
deg = np.array([0,30,45,60,90])

In [8]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [9]:
np.cos(deg*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [10]:
np.tan(deg*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [11]:
'''
arcsin
arccos
arctan
'''

'\narcsin\narccos\narctan\n'

In [12]:
ArrayLast = np.array([0,1,0,8,-2,2,-9.87])

In [14]:
np.floor(ArrayLast)

array([  0.,   1.,   0.,   8.,  -2.,   2., -10.])

In [15]:
np.ceil(ArrayLast)

array([ 0.,  1.,  0.,  8., -2.,  2., -9.])

In [16]:
array_1d = np.array([1,2,3,4,5])

In [17]:
array_1d[0]

1

In [19]:
array_1d[-1]

5

In [20]:
array_1d[1:3]

array([2, 3])

In [21]:
array_1d[2:]

array([3, 4, 5])

In [22]:
array_2d = np.array([[1,2,3],[5,6,7]])

In [23]:
array_2d[0,1]

2

In [24]:
array_2d[0][1]

2

In [25]:
array_2d[1:2]

array([[5, 6, 7]])

In [26]:
array_2d[1,-1]

7

In [29]:
array_3d = np.array([[[1,2,3],[7,8,9]],[[1,2,3],[7,8,9]]])

In [30]:
array_3d.shape

(2, 2, 3)

In [31]:
array_3d[1,1,-1]

9